import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { MainLinkButton } from "~/component/MainLinkButton";

function HeroBanner() {
  return (
    <section className="mt-12 mb-24 grid grid-cols-1 sm:grid-cols-2 gap-12 px-8 sm:mt-36">
      <div className="flex flex-col gap-4">
        <h1 className="text-6xl">Generate icons with a click of a button</h1>
        <p className="text-2xl">Use AI to generate instead of waiting for a graphic designer.</p>
        <MainLinkButton href="/generate" className="self-start">
        Generate an Icon
        </MainLinkButton>
      </div>
      <Image
         src="/banner.png" 
         alt="Icon Generator" 
         width={800} 
         height={400} 
         className="order-first sm:-order-none"/>
    </section>
    );
}

const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Icon Generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex flex-col items-center justify-center">
        <HeroBanner />
      </main>
    </>
  );
};

export default HomePage;
